import {StyleSheet} from 'react-native';

export const BORDER = '#E2E4E9';

export const styles = StyleSheet.create({
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: BORDER,
    paddingTop: 8,
    paddingBottom: 10,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
  },
  iconWrap: {
    width: 40,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 3,
  },
  iconWrapActive: {
    backgroundColor: '#E6EDFE',
  },
  label: {fontSize: 11, color: '#9CA3AF', fontWeight: '600'},
  labelActive: {color: '#1955F0'},

  // --- More sheet ---
  backdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  sheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 10,
    maxHeight: '85%',
  },
  grabber: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#E2E4E9',
    alignSelf: 'center',
    marginBottom: 14,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  sheetLogoWrap: {
    width: 100,
    height: 40,
    borderRadius: 8,
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: '#fff',
  },
  sheetLogo: {
    width: '100%',
    height: '100%',
  },
  sheetHeaderTitle: {fontSize: 16, fontWeight: '700', color: '#111827'},
  sheetHeaderSubtitle: {fontSize: 12, color: '#9CA3AF', marginTop: 1},
  sheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 10,
    marginBottom: 2,
  },
  sheetItemActive: {
    backgroundColor: '#E6EDFE',
  },
  sheetItemIcon: {marginRight: 14},
  sheetItemText: {fontSize: 15, color: '#374151', fontWeight: '500'},
  sheetItemTextActive: {color: '#1955F0', fontWeight: '700'},
  sheetItemTextDisabled: {color: '#D1D5DB'},
  sheetFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: BORDER,
  },
  sheetUserRow: {flexDirection: 'row', alignItems: 'center'},
  sheetAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#E6EDFE',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  sheetAvatarText: {color: '#1955F0', fontWeight: '700', fontSize: 13},
  sheetUserName: {fontSize: 14, fontWeight: '700', color: '#111827'},
  sheetUserSub: {fontSize: 12, color: '#9CA3AF'},
});