import {StyleSheet} from 'react-native';

export const NAVY = '#0E1B4D';
export const BLUE = '#3B5BFF';
export const PURPLE = '#6D3BEB';
export const GRAY = '#6B7280';
export const BG = '#F2F4FC';

export const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: BG},
  container: {
    flex: 1,
    paddingHorizontal: 22,
    paddingTop: 24,
    paddingBottom: 30,
  },

  // ---- Decorative background ----
  topDecorWrap: {
    position: 'absolute',
    top: -40,
    right: -70,
    width: 300,
    height: 300,
  },
  topDecorBlob: {
    position: 'absolute',
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: '#E1E6FB',
    opacity: 0.9,
  },
  topDecorArcOuter: {
    position: 'absolute',
    top: 60,
    left: -20,
    width: 260,
    height: 260,
    borderRadius: 130,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.6)',
  },
  topDecorArcInner: {
    position: 'absolute',
    top: 105,
    left: -45,
    width: 285,
    height: 285,
    borderRadius: 142,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.4)',
  },
  topDecorArcFar: {
    position: 'absolute',
    top: 10,
    left: 20,
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.35)',
  },

  bottomDecorWrap: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 200,
  },
  bgWaveDeep: {
    position: 'absolute',
    bottom: -190,
    left: -60,
    right: -60,
    height: 300,
    borderRadius: 999,
    backgroundColor: '#C7CFFA',
    opacity: 0.4,
  },
  bgWaveMid: {
    position: 'absolute',
    bottom: -158,
    left: -40,
    right: -40,
    height: 250,
    borderRadius: 999,
    backgroundColor: '#DBE0FB',
    opacity: 0.7,
  },
  bgWaveFront: {
    position: 'absolute',
    bottom: -132,
    left: -30,
    right: -30,
    height: 210,
    borderRadius: 999,
    backgroundColor: '#EAEDFC',
    opacity: 0.95,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.7)',
  },

  // ---- Header ----
  logoWrap: {alignItems: 'center', marginTop: 12, marginBottom: 26},
  logo: {width: 220, height: 70},
  brand: {color: GRAY, fontWeight: '500', fontSize: 14, letterSpacing: 0.3, marginTop: 2},

  title: {
    color: NAVY,
    fontSize: 27,
    fontWeight: '800',
    textAlign: 'center',
    lineHeight: 35,
  },
  titleAccent: {color: BLUE},

  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 14,
    marginBottom: 14,
    gap: 8,
  },
  dividerLine: {width: 26, height: 1.5, backgroundColor: '#C4CBF5'},
  dividerDot: {width: 6, height: 6, borderRadius: 3, backgroundColor: BLUE},

  subtitle: {
    color: GRAY,
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 21,
    marginBottom: 30,
  },

  // ---- Option cards ----
  cardRow: {flexDirection: 'row', gap: 14, marginBottom: 28},
  card: {
    flex: 1,
    borderRadius: 22,
    backgroundColor: '#fff',
    paddingTop: 26,
    paddingBottom: 22,
    paddingHorizontal: 14,
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: '#3949AB',
    shadowOpacity: 0.1,
    shadowRadius: 14,
    shadowOffset: {width: 0, height: 8},
    elevation: 4,
  },
  cardWaveBack: {
    position: 'absolute',
    left: -8,
    right: -8,
    height: 180,
    bottom: -140,
    borderRadius: 999,
    opacity: 0.5,
  },
  cardWaveMid: {
    position: 'absolute',
    left: -8,
    right: -8,
    height: 150,
    bottom: -114,
    borderRadius: 999,
    opacity: 0.75,
  },
  cardWaveFront: {
    position: 'absolute',
    left: -8,
    right: -8,
    height: 120,
    bottom: -90,
    borderRadius: 999,
    opacity: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.6)',
  },
  cardIconBox: {
    width: 60,
    height: 60,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 16.5,
    fontWeight: '800',
    color: NAVY,
    textAlign: 'center',
    marginBottom: 8,
  },
  cardSubtitle: {
    fontSize: 12,
    lineHeight: 17,
    color: GRAY,
    textAlign: 'center',
    marginBottom: 20,
  },
  cardArrowBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.18,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 3},
    elevation: 3,
  },

  // ---- Trust badges ----
  trustRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  trustItem: {alignItems: 'center', paddingHorizontal: 14},
  trustIconBox: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 7,
  },
  trustLabel: {fontSize: 10.5, lineHeight: 13, color: GRAY, textAlign: 'center'},
  trustDivider: {width: 1, height: 28, backgroundColor: '#DADFF7'},
});