import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {flex: 1, backgroundColor: '#e6e8f3'},
  container: {padding: 16, paddingBottom: 100},

  headerRow: {marginBottom: 16},
  title: {fontSize: 20, fontWeight: '800', color: '#0B1E45', letterSpacing: -0.3},
  subtitle: {fontSize: 12.5, color: '#6B7280', marginTop: 3},

  searchInput: {
    backgroundColor: '#dbdbea',
    borderWidth: 1,
    borderColor: '#EEF0F4',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 13,
    color: '#111827',
    marginBottom: 18,
    shadowColor: '#1E293B',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
  },

  emptyWrap: {paddingVertical: 48, alignItems: 'center'},
  emptyText: {color: '#9CA3AF', fontSize: 13, fontWeight: '500'},

  // Card — premium floating shadow + colored left accent (blue, matches investor id)
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    borderLeftWidth: 4,
    borderLeftColor: '#600a6d',
    padding: 16,
    marginBottom: 14,
    shadowColor: '#1E293B',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.1,
    shadowRadius: 14,
    elevation: 4,
  },
  cardTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  investorId: {
    fontSize: 10.5,
    fontWeight: '700',
    color: '#2563EB',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    alignSelf: 'flex-start',
    letterSpacing: 0.3,
  },
  investorName: {fontSize: 16, fontWeight: '800', color: '#0F172A', marginTop: 6, letterSpacing: -0.2},
  eyeBtn: {
    width: 32,
    height: 32,
    borderRadius: 9,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#EEF0F4',
    alignItems: 'center',
    justifyContent: 'center',
  },

  cardGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F6FA',
  },
  cardCol: {flex: 1},
  cardLabel: {fontSize: 9.5, color: '#9CA3AF', fontWeight: '700', letterSpacing: 0.5, textTransform: 'uppercase'},
  cardValue: {fontSize: 14.5, fontWeight: '700', color: '#111827', marginTop: 4},
  cardValueSm: {fontSize: 12.5, color: '#374151', fontWeight: '500', marginTop: 4},

  pillRow: {
    flexDirection: 'row',
    marginTop: 4,
    gap: 24,
  },
  pillGroup: {alignItems: 'flex-start'},
  pillGroupLabel: {fontSize: 9.5, color: '#9CA3AF', fontWeight: '700', marginBottom: 5, letterSpacing: 0.5, textTransform: 'uppercase'},

  pill: {paddingHorizontal: 10, paddingVertical: 5, borderRadius: 8},
  pillText: {fontSize: 10.5, fontWeight: '700'},
  pillApproved: {backgroundColor: '#DCFCE7'},
  pillTextApproved: {color: '#16A34A'},
  pillRejected: {backgroundColor: '#FEE2E2'},
  pillTextRejected: {color: '#DC2626'},
  pillPending: {backgroundColor: '#FEF3C7'},
  pillTextPending: {color: '#D97706'},
});